# Generated by Django 3.2.7 on 2021-10-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id']},
        ),
    ]
